### PR TITLE
Fix no-intro captcha failure, add parent-clone

### PR DESCRIPTION
**Pull request by ReenigneArcher**
-Fix no-intro captcha failure
-Add support for parent-clone as well as standard dats

### CODE REVIEW

**Comment by ReenigneArcher** [comment]
I made some tweaks in this [fork](https://github.com/RetroArcher-research/dats) to add support for parent-clone as well as other changes for my own usage... and discovered an issue with the captcha on dat-o-matic. I then fixed the issue; however I made several other changes in that repo, so replicated these fixes for this pull request.

Let me know if you have any questions.

**Comment by ReenigneArcher** [comment]
Also the action you are using to create a release is not working to update assets anymore, if they already exist. What I ended up doing is creating a new release based on the timestamp when the workflow runs. You can see an example in the fork I linked previously if you want to incorporate something similar. Cheers!

**Review by hugo19941994 — APPROVED** [review]
Oh thanks for this, it looks great. It's been a few months since I've updated my sets so I wasn't even aware of the new captcha stuff.

**Comment by ReenigneArcher** [comment]
No problem. I don't think it's new, it's just random. Sometimes it does not display the captcha in which case your old script would work fine. Cheers!

**Pull request merged**
